site_name: All Things Cloud
theme:
  name: material
  features:
    - navigation.sections
plugins:
  - blog:
      blog_dir: .
      post_url_format: "{file}"
  - meta
  - search
  - tags
nav:
  - index.md
extra:
  generator: false
  analytics:
    provider: google
    property: G-QRXFBQ7G6G
