site_name: All Things Cloud
theme:
  name: material
  custom_dir: custom/
  features:
    - navigation.sections
plugins:
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
      archive: false
  - meta
  - search
  - tags
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
nav:
  - index.md
  - koverholt.com: https://koverholt.com
extra:
  generator: false
  analytics:
    provider: google
    property: G-QRXFBQ7G6G
