site_name: All Things Cloud
theme:
  name: material
  custom_dir: custom/
  features:
    - navigation.sections
plugins:
  - blog:
      blog_dir: .
      post_url_format: "{file}"
      archive: false
  - meta
  - search
  - tags
markdown_extensions:
  - attr_list
nav:
  - index.md
extra:
  generator: false
  analytics:
    provider: google
    property: G-QRXFBQ7G6G
